### ISSUE TITLE
Polyfilling sha256

### ISSUE THREAD

**Issue by mentalisttraceur** [jstrieb/just.sh#1]
You have a comment in the readme about being unable to make sha256 portable without relying on Python.

Well, there's at least partial progress to be made by using `shasum` as a fallback. For example:

```sh
if command -v sha256sum >/dev/null
then
    sha256sum ...
else
    shasum -a 256 ...
fi
```

I believe this will cover basically every modern practically usable system that has a `/bin/sh`.

In particular, to my knowledge/memory, this covers

1. basically every Linux distro (`sha256sum` installed by default),
2. Git Bash, BusyBox-w32, and the like on Windows, and
3. MacOS (`shasum` installed by default).

**Comment by mentalisttraceur** [comment]
If neither exists, yet another option which might be available in places Python isn't is the `openssl` CLI: `openssl sha256`, although that has a different output format than the already mentioned.

**Comment by jstrieb** [comment]
Thanks for raising this! It took a while to get to, but is now implemented.
